---

- name: Get default gateway IP Address
  shell: >
    ip route | grep default | awk '{print $3}'
  register: local_service_ip_output

- set_fact:
    local_service_ip: "{{ local_service_ip_output.stdout }}"

- block:
    - include: ubuntu.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - include: freebsd.yml
      when: ansible_distribution == 'FreeBSD'

    - name: Install tools
      package: name="{{ item }}" state=present
      with_items:
        - "{{ tools|default([]) }}"
      tags:
        - always

    - name: Sysctl tuning
      sysctl: name="{{ item.item }}" value="{{ item.value }}"
      with_items:
        - "{{ sysctl|default([]) }}"
      tags:
        - always

    - meta: flush_handlers
  rescue:
    - debug: var=fail_hint
      tags: always
    - fail:
      tags: always
